### ISSUE TITLE
'GcoreBox' object has no attribute 'info_dict'

### ISSUE THREAD

**Issue by zeafynx** [yihong0618/gaycore#12]
macOS 10.14
python 3
运行gaycore命令，随便选一个，比如最近电台，然后会出现这个错误。麻烦看看哈

**Comment by yihong0618** [comment]
@zeafynx 试试按右键或者l？

**Comment by yihong0618** [comment]
> @zeafynx 试试按右键或者l？

@zeafynx  是个bug，我更新下。 但是目前是能用的 右键和`l`是进入下一页。不是 enter, enter 是选中电台播放

**Comment by yihong0618** [comment]
@zeafynx  更新了

**Comment by zeafynx** [comment]
感谢！更新给力

**Comment by yihong0618** [comment]
@zeafynx 客气了。
