### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by catbaron0** [yihong0618/gaycore#4]
1. 「左右/hl」来控制「进入/退出」有点奇怪……？而且确认播放的时候是回车（一开始我以为一路 右右右 就行了……）
在浏览单时候还好，但感觉在播放的时候左右来控制播放进度会更自然一些。

2. 浏览时选中的条目也许保持高亮会比较好

3. 「o 打开信息来源」有提示，「Enter 打开图片」为啥没有……

**Comment by yihong0618** [comment]
1. 因为好多目录只有一页，误操作就播放了直接。
2. 这个我想了，后期会争取改一下
3. 考虑会加上。
4. 谢谢建议

**Comment by yihong0618** [comment]
当时没加enter看图片的原因是怕造成误解，因为o是任意地方都可以打开来源，而enter看图片必须在时间轴的box里。
