### ISSUE TITLE
不知道怎么描述 但是 界面好像有一点点问题

### ISSUE THREAD

**Issue by Borber** [yihong0618/gaycore#5]
![image](https://user-images.githubusercontent.com/30563826/53536425-523aa980-3b41-11e9-9466-c8c206f902c9.png)

**Comment by yihong0618** [comment]
每次都是这样还是复现？我mac未出现这个问题。我研究一下啊~

**Comment by Borber** [comment]
每次都是这样 平台 manjaro gnome 终端konsole

**Comment by yihong0618** [comment]
是按上下键之后出现么？

**Comment by Borber** [comment]
是的 下级目录也会发生这种情况

**Comment by yihong0618** [comment]
好的，我研究一下。你先试试其它终端有这个问题么？

**Comment by yihong0618** [comment]
查了下，不确定可能是这个问题https://github.com/Tetralet/LilyTerm/issues/127

**Comment by Borber** [comment]
试了 gnome的 还是有这个问题

**Comment by Borber** [comment]
好 我去看看

**Comment by Borber** [comment]
应该不是 256色的原因 konsole是支持256真色的

**Comment by yihong0618** [comment]
https://unix.stackexchange.com/questions/394834/ncurses-not-displaying-window-border-correctly-in-gnome-terminal

**Comment by yihong0618** [comment]
你放大一下窗口看看 会不会解决这个问题

**Comment by yihong0618** [comment]
就是出现这个问题后 把窗口放大一下（最大化就行）

**Comment by Borber** [comment]
最大化也是这样 
![image](https://user-images.githubusercontent.com/30563826/53538433-93828780-3b48-11e9-998a-5c4cdd26e29d.png)

**Comment by yihong0618** [comment]
那理论来说是终端问题了，因为最大化的时候会强制clear整个页面

**Comment by Borber** [comment]
好吧 我再自己看看 项目很好大佬加油

**Comment by yihong0618** [comment]
好的，我也再看看，谢谢你
