### ISSUE TITLE
feature request: no TUI

### ISSUE THREAD

**Issue by gaoryrt** [yihong0618/gaycore#7]
选择界面太扎眼了，老板走过来就知道我在摸鱼，希望出一个没有界面的版本
参考 https://github.com/terkelg/prompts

**Comment by NamelessAshone** [comment]
@gaoryrt 这个是Node的库吧, gaycore是用Python写的, 请问有类似的Python库吗?

**Comment by gaoryrt** [comment]
@NamelessAshone https://github.com/Mckinsey666/bullet

**Comment by NamelessAshone** [comment]
@gaoryrt 这个库很棒! 感谢
