### ISSUE TITLE
提供两个 API

### ISSUE THREAD

**Issue by XinoAssassin** [yihong0618/gaycore#8]
https://www.gcores.com/api/categories/9/originals?page=1&auth_exclusive=dpkynzs2q0wm9o5gi1r83fcabthl4eu

https://www.gcores.com/api/volumes/107287/timelines?&auth_exclusive=dpkynzs2q0wm9o5gi1r83fcabthl4eu

**Comment by yihong0618** [comment]
非常感谢。
